language: go
sudo: false

go:
  - "1.11"
  - "1.12"
  - "stable"

services:
  - mysql

addons:
  postgresql: "5.6"

env:
  global:
    - MY_URI="root@tcp(localhost:3306)/mutex"

before_install:
  - mysql -e 'CREATE DATABASE mutex;'
  - env GO111MODULE=on go mod vendor

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
